In [2]:
#Q1
import numpy as np
b=np.array([int(x==4) for x in range(10)])
print(b)

[0 0 0 0 1 0 0 0 0 0]


In [6]:
#Q2
import numpy as np
c=np.arange(10,50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#Q3
import numpy as np
a=np.random.randint(0,9,size=(3,3)) 
print(a)

[[3 8 7]
 [1 1 3]
 [5 7 7]]


In [14]:
#Q4
import numpy as np
arr = np.array([1,2,0,0,4,0]) 
print ("Input  array : \n", arr)   
arr_nonzero = np.nonzero(arr)
print ("Indices of non zero elements : ", arr_nonzero) 

Input  array : 
 [1 2 0 0 4 0]
Indices of non zero elements :  (array([0, 1, 4], dtype=int64),)


In [19]:
#Q5
import numpy as np
p=np.random.randint(0,100,size=(10,10)) 
print(p)
q=p.flatten()
min=q.min()
max=q.max()
print("min value is :", min)
print("max value is :", max)


[[27 33 29 46 28 18 92 21 37 14]
 [60  1 83  1 91 80 14 44 57 96]
 [21 96 91 69  1 49 27 78 24 42]
 [30 92  8  6  2 84 61 55 45 77]
 [19 76 98 36 14 18 79 40 85  0]
 [78 83 15 19 31 22 15 37 21 14]
 [73 71 29 29 87 23 59 52 56 50]
 [94 78 92 52  7 83 16 73 31 66]
 [10 48 81 29 41 60 96 40 13 37]
 [39 34 73 74 92 96 96 10 36 47]]
min value is : 0
max value is : 98


In [26]:
#Q6
import numpy as np
r = np.random.rand(30)
print(r)
print(r.size)
m = r.mean()
print (m)

[0.51680385 0.53470625 0.27530505 0.3823631  0.15476006 0.38585581
 0.50983744 0.75207129 0.56957075 0.42121627 0.05515212 0.47720601
 0.66209124 0.49312956 0.00523519 0.54440405 0.69356338 0.94760261
 0.5624377  0.5138258  0.01521019 0.79139985 0.22355833 0.70584056
 0.18856219 0.25693702 0.40493899 0.90907023 0.52534252 0.41301262]
30
0.46303366819142533
